language: ruby
rvm: 2.3.3

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 5c92b41b364eb925b2b10a46544366449d2ae05a1d50bd9624f4abc638374541

notifications:
  email: false

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate

install: bundle install --jobs=3 --retry=3
after_success: bundle exec codeclimate-test-reporter
script: bundle exec rspec
