dist: trusty
language: ruby
rvm: 2.3.3

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: db082b1209129f33eff8a99b0b60004964f4043f44467bcb294ef748fee3698f

notifications:
  email: false

before_install: gem update --system

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate

install: bundle install --jobs=3 --retry=3
after_success: bundle exec codeclimate-test-reporter
script: bundle exec rspec
